# Valid TOML config file
# Don't forget to change <user> with your user
genesis-file="./genesis.json"
data-path="./data" 
host-allowlist=["*"]
min-gas-price=0

#Peers
p2p-port=P2PDEFAULT
max-peers=42

#rcp
rpc-http-enabled=true
rpc-http-port=RCPDEFAULT
rpc-http-cors-origins=["*"]
rpc-http-api=[ 'ADMIN', 'ETH', 'NET', 'WEB3', 'CLIQUE', 'IBFT', 'PERM', 'DEBUG', 'MINER', 'EEA', 'PRIV', 'TXPOOL']

# Mining
miner-enabled=true
miner-coinbase="0xfe3b557e8fb62b89f4916b721be55ceb828dbd73"

# permissions
permissions-nodes-config-file-enabled=true
permissions-accounts-config-file-enabled=true
permissions-nodes-config-file="./data/permissions_config.toml"
permissions-accounts-config-file="./data/permissions_config.toml"

# Privacy
# privacy-enabled=false
# privacy-public-key-file="./orion/node1Key.pub"
# privacy-url="http://localhost:8880"