
#Stage 0, basado en node.js
FROM node:16.16.0-alpine as node
WORKDIR /app
COPY ./ /app/
RUN npm install
RUN npm run build

#Stage 1, basado en nginx
FROM nginx:alpine as nginx
COPY --from=node /app/dist/demo-energia-mvm /usr/share/nginx/html
COPY ./nginx-custom.conf /etc/nginx/conf.d/default.conf
